on:
  pull_request:
  push: { branches: [main] }

name: ci
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Fetch Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Check Rust code formatting
        run: cargo fmt --check

      - name: Check Nix code formatting
        run: nix fmt -- *.nix --check

      - name: Run tests
        run: nix develop --command cargo test
