on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

name: update-manifests
jobs:
  update-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Fetch Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Generate manifests
        run: nix develop --command cargo run

      - name: Commit manifests
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update package manifests
          file_pattern: "manifests.nix"
